#!/usr/bin/env bash

# This script is displaying "Best School" 10 times

count=0

while [ $count -lt 10 ]
do
  echo "Best School"
  (( count++ ))
done

#i=1

#while [ $i ];
#do
#	echo "Best School";
#	let i++;
#
#	if [[ $i==10 ]];
#	then
#		break
#	fi
#done
