#!/usr/bin/env bash

# while loop

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done

#i=1
#while [[ $i ]]
#do
#	echo "Best School";
#	let i++;
#	
#	if [[ $i == 9 ]];
#	do
#		echo "Hi";
#	else
#		continue
#	fi
#done

