#!/usr/bin/env bash

# loop using while elif and else

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck"
  elif [ $count -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done

#i= 1
#while (( i < 10 ));
#do
#	if(( i == 4 ));
#	do
#		echo "bad luck"
#	elif(( i == 8 ));
#	do
#		echo "good luck"
#	else;
#	do
#		echo "Best school"
#	fi
#done
