#!/usr/bin/env bash

# loop using while elif and else

i= 1
while (( i < 10 ));
do
	if(( i == 4 ));
	do
		echo "bad luck"
	elif(( i == 8 ));
	do
		echo "good luck"
	else;
	do
		echo "Best school"
	fi
done
