#!/usr/bin/env bash
#using whle loop and case

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done

#i=1
#while(( i < {1..20} ));
#do
#	if(( i == 4 ));
#	do
#		echo "bad luck from China"
#	elif(( i == 9));
#	do
#		echo "bad luck from Japan"
#	elif(( i == 17 ));
#	do
#		echo "bad luck from Italy"
#	fi
#done
