#!/usr/bin/env bash
#using whle loop and case

i=1
while(( i < {1..20} ));
do
	if(( i == 4 ));
	do
		echo "bad luck from China"
	elif(( i == 9));
	do
		echo "bad luck from Japan"
	elif(( i == 17 ));
	do
		echo "bad luck from Italy"
	fi
done
